### ISSUE TITLE
How can we believe that the repo will track NTL

### ISSUE THREAD

**Issue by christianpeel** [cryptobiu/NTL#1]
I think it's great that you've made a git mirror of NTL.  I'm curious what 'trusted' means; do you have support or participation from Mr Shoup?     I notice that Mr Shoup didn't respond to  http://shoup.net/pipermail/ntl_shoup.net/2015-January/000056.html

**Comment by moriyaw** [comment]
We added the NTL version that we uses in Scapi to Github as we did to all other libraries we use (and were not at github yet).
Currently, this version works fine for us. 

We do not garuntee support in the NTL library.

**Comment by sanpitch** [comment]
Thanks.  I guess that you're just trying to be transparent about the code that you use.  Thank you for the update.

**Comment by christianpeel** [comment]
Thanks. I now understand that you're just trying to be transparent with the code that you're using.
